server:
  port: 9000
  
spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
      
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ccc
    username: root
    password: puseon
