server: 
  port: 9000

 
spring: 
  mvc: 
    view: 
      suffix: .jsp
      prefix: /
  datasource: 
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/a?characterEncoding=UTF-8
      username: root
      password: puseon