package com.woniu.mapper;

import com.woniu.entity.UCExample;
import com.woniu.entity.UCKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UCMapper {
	UCKey selectByid(UCKey key);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_c
     *
     * @mbggenerated Sat Apr 13 11:24:13 CST 2019
     */
    int countByExample(UCExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_c
     *
     * @mbggenerated Sat Apr 13 11:24:13 CST 2019
     */
    int deleteByExample(UCExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_c
     *
     * @mbggenerated Sat Apr 13 11:24:13 CST 2019
     */
    int deleteByPrimaryKey(UCKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_c
     *
     * @mbggenerated Sat Apr 13 11:24:13 CST 2019
     */
    int insert(UCKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_c
     *
     * @mbggenerated Sat Apr 13 11:24:13 CST 2019
     */
    int insertSelective(UCKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_c
     *
     * @mbggenerated Sat Apr 13 11:24:13 CST 2019
     */
    List<UCKey> selectByExample(UCExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_c
     *
     * @mbggenerated Sat Apr 13 11:24:13 CST 2019
     */
    int updateByExampleSelective(@Param("record") UCKey record, @Param("example") UCExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_c
     *
     * @mbggenerated Sat Apr 13 11:24:13 CST 2019
     */
    int updateByExample(@Param("record") UCKey record, @Param("example") UCExample example);
}