package com.woniu.entity;

public class Student {
	private Teacher teacher;
	private Subject subject; 
	
    public Teacher getTeacher() {
		return teacher;
	}

	public void setTeacher(Teacher teacher) {
		this.teacher = teacher;
	}

	public Subject getSubject() {
		return subject;
	}

	public void setSubject(Subject subject) {
		this.subject = subject;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stid
     *
     * @mbggenerated Fri Apr 12 15:20:44 CST 2019
     */
    private Integer stid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stname
     *
     * @mbggenerated Fri Apr 12 15:20:44 CST 2019
     */
    private String stname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.score
     *
     * @mbggenerated Fri Apr 12 15:20:44 CST 2019
     */
    private Integer score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.subjectid
     *
     * @mbggenerated Fri Apr 12 15:20:44 CST 2019
     */
    private Integer subjectid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.teacherid
     *
     * @mbggenerated Fri Apr 12 15:20:44 CST 2019
     */
    private Integer teacherid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stid
     *
     * @return the value of student.stid
     *
     * @mbggenerated Fri Apr 12 15:20:44 CST 2019
     */
    public Integer getStid() {
        return stid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stid
     *
     * @param stid the value for student.stid
     *
     * @mbggenerated Fri Apr 12 15:20:44 CST 2019
     */
    public void setStid(Integer stid) {
        this.stid = stid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stname
     *
     * @return the value of student.stname
     *
     * @mbggenerated Fri Apr 12 15:20:44 CST 2019
     */
    public String getStname() {
        return stname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stname
     *
     * @param stname the value for student.stname
     *
     * @mbggenerated Fri Apr 12 15:20:44 CST 2019
     */
    public void setStname(String stname) {
        this.stname = stname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.score
     *
     * @return the value of student.score
     *
     * @mbggenerated Fri Apr 12 15:20:44 CST 2019
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.score
     *
     * @param score the value for student.score
     *
     * @mbggenerated Fri Apr 12 15:20:44 CST 2019
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.subjectid
     *
     * @return the value of student.subjectid
     *
     * @mbggenerated Fri Apr 12 15:20:44 CST 2019
     */
    public Integer getSubjectid() {
        return subjectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.subjectid
     *
     * @param subjectid the value for student.subjectid
     *
     * @mbggenerated Fri Apr 12 15:20:44 CST 2019
     */
    public void setSubjectid(Integer subjectid) {
        this.subjectid = subjectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.teacherid
     *
     * @return the value of student.teacherid
     *
     * @mbggenerated Fri Apr 12 15:20:44 CST 2019
     */
    public Integer getTeacherid() {
        return teacherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.teacherid
     *
     * @param teacherid the value for student.teacherid
     *
     * @mbggenerated Fri Apr 12 15:20:44 CST 2019
     */
    public void setTeacherid(Integer teacherid) {
        this.teacherid = teacherid;
    }
}