package com.woniu.entity;

public class Subject {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subject.subjectid
     *
     * @mbggenerated Fri Apr 12 15:20:44 CST 2019
     */
    private Integer subjectid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subject.subjectname
     *
     * @mbggenerated Fri Apr 12 15:20:44 CST 2019
     */
    private String subjectname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subject.subjectid
     *
     * @return the value of subject.subjectid
     *
     * @mbggenerated Fri Apr 12 15:20:44 CST 2019
     */
    public Integer getSubjectid() {
        return subjectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subject.subjectid
     *
     * @param subjectid the value for subject.subjectid
     *
     * @mbggenerated Fri Apr 12 15:20:44 CST 2019
     */
    public void setSubjectid(Integer subjectid) {
        this.subjectid = subjectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subject.subjectname
     *
     * @return the value of subject.subjectname
     *
     * @mbggenerated Fri Apr 12 15:20:44 CST 2019
     */
    public String getSubjectname() {
        return subjectname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subject.subjectname
     *
     * @param subjectname the value for subject.subjectname
     *
     * @mbggenerated Fri Apr 12 15:20:44 CST 2019
     */
    public void setSubjectname(String subjectname) {
        this.subjectname = subjectname;
    }
}