package com.woniu.entity;

public class Teacher {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.teacherid
     *
     * @mbggenerated Fri Apr 12 15:20:44 CST 2019
     */
    private Integer teacherid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.teachername
     *
     * @mbggenerated Fri Apr 12 15:20:44 CST 2019
     */
    private String teachername;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.teacherid
     *
     * @return the value of teacher.teacherid
     *
     * @mbggenerated Fri Apr 12 15:20:44 CST 2019
     */
    public Integer getTeacherid() {
        return teacherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.teacherid
     *
     * @param teacherid the value for teacher.teacherid
     *
     * @mbggenerated Fri Apr 12 15:20:44 CST 2019
     */
    public void setTeacherid(Integer teacherid) {
        this.teacherid = teacherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.teachername
     *
     * @return the value of teacher.teachername
     *
     * @mbggenerated Fri Apr 12 15:20:44 CST 2019
     */
    public String getTeachername() {
        return teachername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.teachername
     *
     * @param teachername the value for teacher.teachername
     *
     * @mbggenerated Fri Apr 12 15:20:44 CST 2019
     */
    public void setTeachername(String teachername) {
        this.teachername = teachername;
    }
}