package com.woniu.entity;

public class UCKey {
	private Category category;
	private User user;
	
    public Category getCategory() {
		return category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_c.cid
     *
     * @mbggenerated Sat Apr 13 11:24:13 CST 2019
     */
    private Integer cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_c.uid
     *
     * @mbggenerated Sat Apr 13 11:24:13 CST 2019
     */
    private Integer uid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_c.cid
     *
     * @return the value of u_c.cid
     *
     * @mbggenerated Sat Apr 13 11:24:13 CST 2019
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_c.cid
     *
     * @param cid the value for u_c.cid
     *
     * @mbggenerated Sat Apr 13 11:24:13 CST 2019
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_c.uid
     *
     * @return the value of u_c.uid
     *
     * @mbggenerated Sat Apr 13 11:24:13 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_c.uid
     *
     * @param uid the value for u_c.uid
     *
     * @mbggenerated Sat Apr 13 11:24:13 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }
}